### ISSUE TITLE
Bug on link parameters

### ISSUE THREAD

**Issue by fabrice4821** [dearhive/dearflip-jquery-flipbook#35]
Hi,

Options :
 //(NON-OPTION) source link for PDF.JS file
    pdfjsSrc: "js/libs/pdf.min.js",
    //(NON-OPTION) source link for PDFcompatibility.JS file
    pdfjsCompatibilitySrc: "js/libs/compatibility.js",
    //(NON-OPTION) source link for PDF.WORKER.JS file
    pdfjsWorkerSrc: "js/libs/pdf.worker.min.js",
    //(NON-OPTION) source link for THREE.JS file
    threejsSrc: "js/libs/three.min.js",
    //(NON-OPTION) source link for MOCKUP.JS file
    mockupjsSrc: "js/libs/mockup.min.js",

doesn't work if dFlipLocation is defined.

**Comment by deepak-ghimire** [comment]
They are relative paths, which take `dFlipLocation` into account.

So your full URL will be: `dFlipLocation + pdfjsSrc`

So always use relative path in those links. Relative to `dFlipLocation`

When `dFlipLocation` is not defined, it's automatically defined by finding the location of the dflip.js script.
Thus `dFlipLocation` always exists.
