### ISSUE TITLE
Fullscreen button not show on Iphone

### ISSUE THREAD

**Issue by fabrice4821** [dearhive/dearflip-jquery-flipbook#36]
I make a test on page :
http://test.gmapfp.org/testj3/

On Pc or android, all works fine.
But on Iphone, the fullscreen button and the page numbers does'nt show.

Thanks for your feedback.

**Comment by deepak-ghimire** [comment]
The fullscreen API is actually lacking in IOS browsers so it cannot be used there. Works in macOS and other devices too.
In the future, if we find any solution for this, then we will add them.
