### ISSUE TITLE
End Page Event to trigger custom function

### ISSUE THREAD

**Issue by mraheelkhan** [dearhive/dearflip-jquery-flipbook#37]
Can we have an event that gets trigger when the user reaches to end of the pdf or to end page(last page).

A function may be trigger upon the event to extend the features.

**Comment by deepak-ghimire** [comment]
Hi,

You can have a look at https://jsfiddle.net/deipghimire/802sLrj1/24/

inside onFLip() function you can conditionally check if current page is last or first and act accordingly.
