### ISSUE TITLE
Support RTL Direction

### ISSUE THREAD

**Issue by sahnounekhaled** [dearhive/dearflip-jquery-flipbook#40]
How to change css or Js file to make this project support RTL PDF File ??

**Comment by deepak-ghimire** [comment]
set 

`direction:"rtl"`

**Comment by sahnounekhaled** [comment]
in which file can i do that ?
thank's lot

**Comment by sahnounekhaled** [comment]
i have download the free version from github

**Comment by deepak-ghimire** [comment]
You can pass that value in settings.

https://dearflip.com/docs/dearflip-jquery/examples/basic-using-options/

**Comment by sahnounekhaled** [comment]
thank you very match

**Comment by LucianPuca** [comment]
@deepak-ghimire I don't want to open a new issue for this, but is there support for top-bottom flipping? I can't find anything in the docs.
 I'm considering using this and having that is part of my checklist. Thanks!

**Comment by deepak-ghimire** [comment]
@LucianPuca are you referring to calendar style top bottom flipping?

**Comment by LucianPuca** [comment]
Correct, exactly that.
