### ISSUE TITLE
Pdf links - demo before purchase

### ISSUE THREAD

**Issue by emmatheuntamed** [dearhive/dearflip-jquery-flipbook#51]
We've installed your free version plugin, and it's looking fantastic! However, we're now thinking about upgrading to the premium version because we need to add links to our PDFs, especially to our images. Is there a demo available that allows us to test out this feature first?

Thanks in advance!

**Comment by deepak-ghimire** [comment]
Test your PDF there:
https://jquery.dearflip.com/pdf-viewer/

**Comment by emmatheuntamed** [comment]
Thank you! The links are working perfectly. However, for every linked element there's a yellow-ish color overlay. Is it possible to remove this?

**Comment by deepak-ghimire** [comment]
Yes you can : https://jquery.dearflip.com/pdf-flipbook-links-customization-and-tips-with-dflip/#change-or-hide-the-color-of-the-links

**Comment by emmatheuntamed** [comment]
Fantastic! Thank you for your fast reply and help.
