### ISSUE TITLE
Do licenses count for DTAP? 

### ISSUE THREAD

**Issue by Jochem-S** [dearhive/dearflip-jquery-flipbook#57]
Hi, 

According to the terms and conditions, a subdomain is considered a site. 

We have a client with a multisite website. We have a DTAP environment for all those websites. For example:

dev.customer1.companyname.nl
dev.customer2.companyname.nl

We have dev, test, acc and production. So 4 environments per client. Only the production environment will be publicly available, the three other environments are purely for testing and demoing. 

Will we have to pay for 4 licenses for just one client, or can we use one license for one client? 

Thanks!

**Comment by deepak-ghimire** [comment]
Hi, 
We use Freemius for licensing and they support dev environments as follows:
https://freemius.com/help/documentation/selling-with-freemius/license-utilization/

So dev.*, test.* is a valid development domain and license quota is not consumed.
but acc.* is not 

if possible use valid staging/development domains.

**Comment by Jochem-S** [comment]
@deepak-ghimire Hi, thanks for your answer. 

Is it possible for Dearfilp to also exclude acc.* with Freemius? We use acc instead of staging, but it's used for the same purpose. Nobody will be able to view the website except for the client with IP whitelisting, so the client will only use that subdomain for testing the package. 

This is important for us because we are building a multisite website, and it would be a waste to have to use 2 licenses for each website when in reality we use one.

**Comment by deepak-ghimire** [comment]
What does "acc" mean?

**Comment by Jochem-S** [comment]
Acceptance. It's the environment where the client can test before the changes to live.

**Comment by deepak-ghimire** [comment]
Ok, We will add that as custom development environment.
Let us know when you have the license.
